services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data/adguard/work:/opt/adguardhome/work
      - ./data/adguard/conf:/opt/adguardhome/conf

  redis:
    image: redis:alpine
    container_name: ntopng_redis
    restart: unless-stopped
    network_mode: "host"
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  ntopng:
    image: ntop/ntopng:latest
    container_name: ntopng
    restart: unless-stopped
    network_mode: "host"
    command: ntopng --community -i any -w 3001
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    depends_on:
      - redis

  api:
    build: ../api
    container_name: rosyst_api
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - ../api/.env
    depends_on:
      - adguardhome
      - ntopng
