services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./data/adguard/work:/opt/adguardhome/work
      - ./data/adguard/conf:/opt/adguardhome/conf
    ports:
      # DNS ports
      - 53:53/tcp
      - 53:53/udp
      # DHCP port
      - 67:67/udp
      - 68:68/udp
      # Web Interface
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      # AdGuard Home initial setup interface
      - 3000:3000/tcp

  redis:
    image: redis:alpine
    container_name: ntopng_redis
    restart: unless-stopped
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  ntopng:
    image: ntop/ntopng:latest
    container_name: ntopng
    restart: unless-stopped
    command: ntopng --community -i any -l 1
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    ports:
      - 3001:3000
    depends_on:
      - redis

  api:
    build: ../api
    container_name: rosyst_api
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - ../api/.env
    depends_on:
      - adguardhome
      - ntopng
